# Copyright (C) 2016 ultical contributors
# 
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU Affero General Public License as published by the Free 
# Software Foundation, either version 3 of the License, or (at your option) any 
# later version.
# 
# If the program is linked with libraries which are licensed under one of the 
# following licenses, the combination of the program with the linked library is 
# not considered a "derivative work" of the program:
# 
# * Apache License, version 2.0
# * Apache Software License, version 1.0
# * Mozilla Public License, versions 1.0, 1.1 and 2.0
# * Common Development and Distribution License (CDDL), version 1.0
# 
# Therefore the distribution of the program linked with libraries licensed under 
# the aforementioned licenses, is permitted by the copyright holders if the 
# distribution is compliant with both the GNU Affero General Public License 
# version 3 and the aforementioned licenses.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the  GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along 
# with this program. If not, see <http://www.gnu.org/licenses/>.
---
version: '2'

services:
  ultical-db:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=ultical
      - MYSQL_PASSWORD=ultical
      - MYSQL_DATABASE=ultical

  ultical-db-config:
    image: peopleplan/liquibase
    depends_on:
      - ultical-db
    links:
      - ultical-db:mysql
    volumes:
      - "../backend/src/main/resources/database/:/changelogs"
    environment:
      - CHANGELOG_FILE=/db.changelog-1.0.xml
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP=unusedbutimagecomplains
      - MYSQL_USER=ultical
      - MYSQL_PASSWORD=ultical
      - MYSQL_ENV_MYSQL_DATABASE=ultical
      - CHANGELOG_FILE=db.changelog-1.0.xml

  ultical-backend:
    build:
      context: ../backend
    depends_on:
      - ultical-db
    links:
      - ultical-db:db
    volumes:
      - "./docker.yaml:/ultical/docker.yaml"
    ports:
        - "8765:8765"
        - "8766:8766"

  ultical-web:
    image: nginx:latest
    links:
      - ultical-backend:backend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./../web:/etc/nginx/html/ultical-web"
      - "./config.js:/etc/nginx/html/ultical-web/config/config.js"
    ports:
      - "80:80"
